#!/bin/sh
#
# e-zk (c) wtfpl 2021
# open a lemonbar instance, providing access to flags via environment vars
# geometry options
#     W       bar width
#     H       bar height
#     X       bar x position
#     Y       bar y position
#     BW      border width
#
# color options
#     BG      background color (hex #[aa]rrggbb)
#     FG      foreground color
#     BC      border color
#     BOT     place bar on bottom (yes/no)
#
# example:
#     (echo "hello!"; sleep 2) | \
#     W=200 H=40 X=20 Y=20 BG=\#000000 FG=\#ffeeee BOT=yes bar

# source config file
test -f $HOME/etc/bar.conf && . $HOME/etc/bar.conf


W=${W:-$width}
H=${H:-$height}
X=${X:-$xpos}
Y=${Y:-$ypos}
BW=${BW:-$borderw}

BG=${BG:-$background}
FG=${FG:-$foreground}
BC=${BC:-$border}
BOT=${BOT:-$bottom}

case "$BOT" in
	[yY]es)	BOT='-b' ;;
	[nN]o)	BOT=''   ;;
	*)	BOT=''   ;;
esac

lemonbar -d $BOT -g ${W}x${H}+${X}+${Y} -f "$font" -f "$font2" -B"$BG" -F "$FG" -u 1 -i $BW -I"$BC" "$@" | sh
