#!/bin/sh
# print colors

def_char="-> " 

horiz() {
	for i in 0 1 2 3 4 5 6 7; do
		printf "\033[3%sm%s\033[0m" "$i" "$char"
	done
	printf "\n"

	for i in 0 1 2 3 4 5 6 7; do
		printf "\033[9%sm%s\033[0m" "$i" "$char"
	done
	printf "\n"
}

vert() {
	for i in 0 1 2 3 4 5 6 7; do
		xcolor=""
		xcolorb=""
		printf "\033[3%sm%s \033[30m\033[4%sm %s \033[0m " "$i" "$xcolor" "$i" "$char"
		printf "\033[9%sm%s \033[30m\033[10%sm %s \033[0m" "$i" "$xcolorb" "$i" "$char"
		printf '\n'
	done
}

short() {
	for i in 0 1 2 3 4 5 6 7; do
		printf "\033[3%sm%s\033[0m" "$i" "$char"
	done
	printf "\n"
}

printf "\n"

case $1 in
	"-v")
		char="${2:-$def_char}"
		vert
		;;
	"-h")
		char="${2:-$def_char}"
		horiz
		;;
	"-s")
		char="${2:-$def_char}"
		short
		;;
	*)
		char="${1:-$def_char}"
		short
		;;
esac

printf "\n"
