#!/bin/sh
# starts picom if it is not running;
# kills picom if it is running

# change this to 'compton' if you use compton
COMMAND=picom
CONFIG=$ETC/picom.conf

if pgrep $COMMAND >/dev/null; then
	echo "killing ${COMMAND}..."
	kill -9 $(pgrep $COMMAND)
else
	echo "starting ${COMMAND}..."

	$COMMAND --experimental-backends --config $CONFIG &
fi
