#!/bin/sh
# starts picom if it is not running;
# kills picom if it is running

if pgrep picom; then
	echo "killing picom..."
	kill -9 $(pgrep picom)
else
	echo "starting picom..."

	picom --config $HOME/etc/compton.conf &
fi
