#!/bin/sh
# wrapper for chrome that changes the homedir, opens discord as a pwa

unset XDG_CONFIG_HOME
unset XDG_CACHE_HOME
export HOME=${HOME}/opt/discord
/usr/local/bin/chrome --app="https://discord.com/" "$@"
