#!/bin/sh
# hex encode a given ip address

INPUT="$1"
SPLIT=`echo "$INPUT" | sed -e 's/\./\ /g'`
OUTPUT="0x"

for part in $SPLIT; do
	HEX=`echo "obase=16; $part" |bc`
	OUTPUT=${OUTPUT}${HEX}
done

echo "$OUTPUT"
