#!/bin/sh
#
# e-zk (c) wtfpl 2021
# hex encode a given ip address

INPUT="$1"
OUTPUT="0x"

IFS='.'
for part in $INPUT; do
	HEX="$(echo "obase=16; $part" | bc |awk '{printf "%02s", $0}')"
	OUTPUT=${OUTPUT}${HEX}
done

echo "$OUTPUT"
