#!/bin/sh
# mount windows drive
# (c) e-zk 2021 wtfpl

DRV="$(echo "${1%%:*}" | tr 'A-Z' 'a-z')"
MNT="${2:-/mnt/${DRV}}"

usage() {
	cat <<EOF
mtdrv: mount a windows drive (requires root)
usage: mtdrv [drive] [mountpoint]
where:
    drive       drive letter (e.g. 'f:' or 'f')
    mountpoint  inode to mount the drive to (optional)
if [mountpoint] is not given the drive will be mounted to '/mnt/[drive]'
EOF
}

case "$1" in "-h"|"--help") usage && exit 0; esac
test $# -ne 1 && usage && exit 1

echo "mounting ${DRV}: at ${MNT}..."
mkdir -p "$MNT"
mount -t drvfs "${DRV}:" "$MNT"
