#!/bin/sh
# mini notification
# usage: notif "message"
# depends: lemonbar, txtw, bar.conf

# load config
test -f $HOME/etc/bar.conf && . $HOME/etc/bar.conf

MESSAGE="  ${1}  "
SKROLL=0
WIDTH=${W:-$(( `txtw -f '$font' -s 16 "x${MESSAGE}x"`))}
if [ $WIDTH -gt 400 ]; then
	export WIDTH=400
	SKROLL=1
fi
HEIGHT=${H:-$height}
BG=${BG:-$background}
FG=${FG:-$foreground}
DELAY=${DELAY:-3}

X=$((1920-WIDTH-20))
Y=20

if [ $SKROLL -eq 1 ]; then
	#WIDTH=200
	(echo "$MESSAGE" | skroll -n 50 -r)
else
	(echo "%{c}$MESSAGE%{l}"; sleep $DELAY)
fi | lemonbar -d -g ${WIDTH}x${HEIGHT}+${X}+${Y} -f "$font" -F $FG -B $BG
