#!/bin/sh
# power menu
# depends: xmenu, xlock

case $(xmenu poweroff reboot sleep hibernate cancel) in
	poweroff)
		(echo "%{c}OFF"; sleep 5) | FG=\#ff0000 bar
		doas shutdown -p now
		;;
	reboot)
		(echo "%{c}REBOOT"; sleep 5) | FG=\#ff0000 bar
		doas reboot
		;;
	sleep)
		xlock & doas zzz
		;;
	hibernate)
		xlock & doas ZZZ
		;;
	*)
		;;
esac
