#!/bin/sh
# power menu
# depends: xmenu, xlock

case $(xmenu poweroff reboot sleep hibernate cancel) in
	poweroff)
		notif "alert:shutdown now" 
		doas shutdown -p now
		;;
	reboot)
		notif "alert:reboot now" 
		doas reboot
		;;
	sleep)
		xlock & doas zzz
		;;
	hibernate)
		xlock & doas ZZZ
		;;
	*)	
		exit 1
		;;
esac
