#!/bin/sh
# take a screenshot using imagemagick
# usage: shot [fname]
# if no filename is specified defaults to the current 'date-time.png'

file=''
ext='.png'
date="$(date '+%F-%T')"

if [ -n "$1" ]; then
	file="${1%%.*}-"
	ext="${1##${file}}"
	ext="${ext:-'.png'}"
fi

fname="${file}${date}${ext}"
import -window root "$fname"
echo "$fname"
