#!/bin/sh
# take a screenshot and append date to filename
# depends: ImageMagick (import)

FILE="${1%%.*}"
EXT="${1##${FILE}}"
DATE="$(date '+%b.%d-%H%M')"

notif "  taking '${FILE}-${DATE}${EXT}'...  "
# wait for a sec
sleep 1
import -window root "${FILE}-${DATE}${EXT}"
notif "  saved '${FILE}-${DATE}${EXT}'  "
