#!/bin/sh
# take a screenshot and append date to filename
# depends: ImageMagick (import)

DATE="$(date '+%b.%d-%H%M')"
if [ -z "$1" ]; then
	FILE=''
	EXT='.png'
	FNAME="${DATE}${EXT}"
else
	FILE="${1%%.*}"
	EXT="${1##${FILE}}"
	FNAME="${FILE}-${DATE}${EXT}"
fi

# notfiy
notif "taking shot..." &

# wait for a sec, then take the scrot
sleep 1
import -window root "${FNAME}"

# notify
notif "saved ${FNAME}" &
