#!/bin/sh
# stacks: multiple bars in one script
# depends: curl, apm, bar.sh, mpc, xtitle

trap die 1 2 3 6 15

# source config file
test -f $HOME/etc/bar.conf && . $HOME/etc/bar.conf

#
PIDPATH=${HOME}/tmp/bar

# stacks on stacks on stacks

# kill the running stacks
die() {
	pkill -KILL lemonbar
	for file in ${PIDPATH}/*; do
		[ -f "$file" ] || continue
		kill -KILL "$(cat ${file})"
		rm -f "${file}"
	done
}

# displays time
clock() {
	# if the pid file exists, then something is running
	if [ -f "${PIDPATH}/clock.pid" ]; then
		echo "error: clock bar is already running!"
		exit 1
	else
		echo "$$" > "${PIDPATH}/clock.pid"
	fi
	while true; do
		#echo "%{c}$(date '+%H:%M:%S') $(date '+%Y.%m.%d')"
		echo "%{c}%{A:notif \"$(date '+%A %d %B')\":}$(date '+%H:%M:%S')%{A}"
		sleep 1
	done | W=$clock_w X=$clock_x Y=$clock_y BG=$clock_bg FG=$clock_fg bar
}

# displays date
datee() {
	while true; do          	
		echo "%{c}$(date '+%d %b')"
		sleep 30
	done | W=$date_w X=$date_x Y=$date_y BG=$date_bg FG=$date_fg bar
}

# displays battery status
bat() {
	# if the pid file exists, then something is running
	if [ -f "${PIDPATH}/bat.pid" ]; then
		echo "error: bat bar is already running!"
		exit 1
	else
		echo "$$" > "${PIDPATH}/bat.pid"
	fi

	local percent status ac color charging
	while true; do
		percent=`apm -l`
		status=`apm -b`
		ac=`apm -a`

		# set color based on battery status (level)
		case "${status}" in
			0)	color="${bat_high}" ;;
			1)	color="${bat_low}"  ;;
			2)	color="${bat_crit}" ;;
			*)	color="\#e00a0a"    ;;
		esac

		# A/C external charger status text
		case "${ac}" in
			0)	charging=""    ;;
			1)	charging="+"   ;;
			2)	charging="++"  ;;
			*)	charging="???" ;;
		esac

		echo "%{c}%{A:power:}${percent}%${charging}%{A}"
		sleep 2
	done | W=$bat_w X=$bat_x Y=$bat_y BG=$bat_bg FG=$bat_fg bar
}

# displays wttr info
wttr() {
	
	# if the pid file exists, then something is running
	if [ -f "${PIDPATH}/wttr.pid" ]; then
		echo "error: wttr bar is already running!"
		exit 1
	else
		echo "$$" > "${PIDPATH}/wttr.pid"
	fi

	while true; do
		DATA=$(curl --connect-timeout 10 wttr.in/${WTTRCITY}?format=%t,%h 2>/dev/null)
		if [ -z "$DATA" ]; then
			TEMP="nil"
			HUM="nil"
		else 	
			TEMP=$(echo $DATA | cut -d ',' -f 1 | sed 's/^+//g')
			HUM=$(echo $DATA | cut -d ',' -f 2)
		fi

		echo "%{c}${TEMP} %{F${accent}}@%{F-} ${HUM} humidity"
		sleep 120
	done | W=$wttr_w X=$wttr_x Y=$wttr_y BG=$wttr_bg FG=$wttr_fg bar
}

# displays current window in scrolling text
title() {
	while true; do
		wintitle="$(xtitle $(pfw))"
		echo "$wintitle" | skroll -n 25 -d0.25 -r
	done | W=200 X=20 Y=20 BG=$foreground FG=$background BOT="-p" bar
}

# displays currently playing track+artist in scrolling text
music() {
	while true; do
		track=""
		if [ ! -z "$(pgrep mpd)" ]; then
			track="$(mpc status --format '%title% // %artist%' | head -n1)"
		else
			track="<<<<<<<<<<<<<<<<"
		fi
		echo "$track" | skroll -n $((($music_w / 10) + 10 )) -r
	done | BOT='yes' W=$music_w X=$music_x Y=$music_y BG=$music_bg FG=$music_fg bar
}


case "$1" in
	"clock") clock ;;
	"date")  datee ;;
	"bat")   bat   ;;
	"wttr")  wttr  ;;
	"music") music ;;
	"title") title ;;
	"kill")  die  ;;
	*)       echo "invalid stack" && exit 1 ;;
esac
