#!/bin/sh
#
# e-zk (c) wtfpl 2021
# tmpfox - generate a temporary firefox profile

# trap anything; clean up
trap cleanup 1 2 3 6 15

# setup homedir + profiledir
FAKEHOME="$(mktemp -d -p /tmp 'firefox.XXXXXX')"
PROFILE_DIR=${FAKEHOME}/firefox

# user agent string to set
# (this one matches the Tor browser)
USER_AGENT="Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0"

# remove the profile dir
cleanup() {
	rm -rvf "$PROFILE_DIR"
	rm -rvf "$FAKEHOME"
}

# create profile directory
mkdir -p "$PROFILE_DIR"

# write user.js settings
cat <<EOF > "${PROFILE_DIR}/user.js"
// user.js //
// change useragent to something inconspicious (windows)
user_pref("general.useragent.override", "${USER_AGENT}");
// disable pocket
user_pref("browser.newtabpage.activity-stream.section.highlights.includePocket", false);

// disable first startup pages 
user_pref("startup.homepage_welcome_url", "");
user_pref("privacy.trackingprotection.introURL", "");

// disable newtab
user_pref("browser.disableResetPrompt", true);
user_pref("browser.newtabpage.enhanced", false);
user_pref("browser.newtabpage.introShown", false);
user_pref("browser.startup.firstrunSkipsHomepage", true);
user_pref("browser.startup.blankWindow", true);
user_pref("browser.selfsupport.url", "");
user_pref("browser.shell.checkDefaultBrowser", false);

// disable javascript by default
user_pref("javascript.enabled", false);
EOF

# link Xauthority
ln -s "${HOME}/.Xauthority" "${FAKEHOME}/.Xauthority"

# force fake HOME dir
export HOME=${FAKEHOME}

# start a new firefox instance w/ the temporary profile directory
MOZ_ACCELERATED=1 firefox-esr --new-instance --no-remote --profile "$PROFILE_DIR"

# remove the profile directory
cleanup
